# -*- coding: utf-8 -*-
"""M_Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AtgE24pYhZHB2BrJrRm3VYMZU0OE4Qnw
"""

!git clone https://github.com/kinit-sk/medical-misinformation-dataset

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, accuracy_score, confusion_matrix

import os

for root, dirs, files in os.walk("/content/medical-misinformation-dataset"):
    for file in files:
        print(os.path.join(root, file))

df = pd.read_csv("/content/medical-misinformation-dataset/sample_data/claims.csv")
df.head()

print(df.columns)
print(df.head())
print(df.isnull().sum())

# CHANGE these names based on dataset
df = df.rename(columns={"statement": "claim", "rating": "label"})
df.head()

df = df[['claim', 'label']].dropna()

df['label'] = df['label'].astype(str).str.lower()

print(df['label'].value_counts())

df['label'] = df['label'].map({
    'true': 1,
    'false': 0,
    'misleading': 0
})

df = df.dropna()

X_train, X_test, y_train, y_test = train_test_split(
    df['claim'],
    df['label'],
    test_size=0.2,
    random_state=42
)

vectorizer = TfidfVectorizer(max_features=5000)

X_train_vec = vectorizer.fit_transform(X_train)
X_test_vec = vectorizer.transform(X_test)

model = LogisticRegression(max_iter=200)
model.fit(X_train_vec, y_train)

y_pred_lr = model.predict(X_test_vec)

print("Logistic Regression Results:\n")
print(classification_report(y_test, y_pred_lr))
print("Accuracy:", accuracy_score(y_test, y_pred_lr))

import seaborn as sns

cm = confusion_matrix(y_test, y_pred_lr)

sns.heatmap(cm, annot=True, fmt='d')
plt.title("Logistic Regression Confusion Matrix")
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.show()

!pip install transformers

from transformers import pipeline

classifier = pipeline(
    "text-classification",
    model="distilbert-base-uncased-finetuned-sst-2-english"
)

bert_preds = []

for text in X_test[:10000]:
    result = classifier(str(text))
    label = result[0]['label']

    if label == 'POSITIVE':
        bert_preds.append(1)
    else:
        bert_preds.append(0)

y_test_subset = y_test[:10000]

print("BERT Results:\n")
print(classification_report(y_test_subset, bert_preds))
print("Accuracy:", accuracy_score(y_test_subset, bert_preds))

lr_acc = accuracy_score(y_test, y_pred_lr)
bert_acc = accuracy_score(y_test_subset, bert_preds)

models = ['Logistic Regression', 'BERT']
accuracy = [lr_acc, bert_acc]

plt.bar(models, accuracy)
plt.title("Model Comparison")
plt.ylabel("Accuracy")
plt.show()

sample = "Drinking hot water cures COVID-19"

print("Logistic Regression Prediction:")
print(model.predict(vectorizer.transform([sample])))

print("\nBERT Prediction:")
print(classifier(sample))
